### ISSUE TITLE
Task deletes do not update on the lists page

### ISSUE THREAD

**Issue by Edison946** [Tuestech/v2#18]
The list of tasks on list page does not automatically update to clear the deleted task.

**Comment by USSiamaboat** [comment]
Reproduced ✅

**Comment by USSiamaboat** [comment]
Fixed in https://github.com/Tuestech/v2/commit/9b5c91ac24ccaad527ec205789839072fa614627

**Comment by USSiamaboat** [comment]
Ensure issues are labeled and assigned appropriately before opening
