### ISSUE TITLE
Poor Dashboard behavior when there are no tasks

### ISSUE THREAD

**Issue by Edison946** [Tuestech/v2#20]
When there are no tasks,
- % complete and % on track display NaN
- Current tasks panel is blank
- Events and Due Dates panel is blank
- Progress and Timing bars are blank

**Comment by USSiamaboat** [comment]
Ensure issues have descriptions, assignments, and labels

**Comment by USSiamaboat** [comment]
Reproduced ✅

**Comment by USSiamaboat** [comment]
Fixed in https://github.com/Tuestech/v2/commit/5a687954994d7ed38c09ec05e6746750e0a787fd
